import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { SelectedProvider } from "@/context/SelectContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Satellite Monitoring System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="emerald">
      <body
        className={`${roboto.variable} font-[family-name:var(--font-roboto)] antialiased`}
      >
        <SelectedProvider>
          {children}
        </SelectedProvider>
      </body>
    </html>
  );
}
